export const EMAIL_VALIDATION_STATUS = {
  EMAIL_SENT: "EMAIL_SENT" as const,
  EMAIL_VERIFY_TIMEOUT: "EMAIL_VERIFY_TIMEOUT" as const,
  EMAIL_VERIFY_FAIL: "EMAIL_VERIFY_FAIL" as const,
  EMAIL_VERIFY_SUCESS: "EMAIL_VERIFY_SUCESS" as const,
} as const;
